name: scc450-slm-llm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - jupyter_client
  - jupyter_console
  - jupyterlab
  - pdfplumber
  - python-dotenv
  - ftfy
  - nltk
  - beautifulsoup4
  - lxml
  - loguru
  - pip

  - pip:
      - pymupdf
      - torch
      - torchvision
      - tf_keras
      # - unstructured
      # - unstructured-ingest
      # - unstructured-client
      - xformers
      - gemma
      - unsloth

      - transformers
      - datasets
