name: scc450-slm-llm
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - jupyter_client
  - jupyter_console
  - jupyterlab
  - pdfplumber
  - python-dotenv
  - ftfy
  - nltk
  - beautifulsoup4
  - lxml
  - pip

  - pip:
      - pymupdf
      - unstructured
      - unstructured-ingest
      - unstructured-client
      - gemma
      - unsloth
      - transformers
      - datasets
